title: QuanTAS: Understanding the limits of Quantum Theory, Algorithms and Systems
logo: /assets/img/QuanTAS_logo.png
description: Supported by nobody yet
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
